# Generated by Django 3.1.5 on 2021-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollevel',
            name='target_school_level',
            field=models.BooleanField(default=True, help_text='Kde chce uživatel učit'),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='user_education',
            field=models.BooleanField(default=True, help_text='Dosažené vzdělání'),
        ),
    ]
