# Generated by Django 3.1.5 on 2021-02-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollevel',
            name='subjects',
            field=models.ManyToManyField(related_name='school_levels', to='teaching.Subject', verbose_name='Předměty'),
        ),
    ]
