# Generated by Django 3.1.5 on 2021-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20210822_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_group',
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subjects',
            field=models.ManyToManyField(to='teaching.Subject', verbose_name='Předměty'),
        ),
    ]
