# Generated by Django 3.1.5 on 2021-09-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20210921_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgroup',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.subject', verbose_name='Předměty'),
        ),
    ]
