# Generated by Django 3.1.5 on 2021-09-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20210928_1359'),
        ('teaching', '0003_auto_20210921_1652'),
    ]

    operations = [
    ]
