# Generated by Django 3.1.5 on 2021-10-17 10:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualifications', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Název školy', max_length=200, unique=True)),
                ('type', models.CharField(choices=[('univerzitni', 'univerzitní'), ('neuniverzitni', 'neuniverzitní'), ('jazykova skola', 'jazyková škola')], help_text='Typ', max_length=20)),
                ('form', models.CharField(choices=[('soukroma', 'soukromá'), ('statni', 'státní'), ('verejna', 'veřejná')], help_text='Forma', max_length=20)),
                ('address', models.CharField(help_text='Adresa', max_length=200)),
                ('rid', models.CharField(help_text='RID', max_length=20, unique=True)),
                ('ic', models.CharField(help_text='IČ', max_length=20)),
                ('databox', models.CharField(help_text='Datová schránka', max_length=20)),
                ('url', models.URLField(help_text='URL')),
                ('code', models.CharField(help_text='Zkratka', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Vysoká škola',
                'verbose_name_plural': 'Vysoké školy',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Název fakulty', max_length=200)),
                ('rid', models.CharField(help_text='RID', max_length=20)),
                ('url', models.URLField(help_text='URL')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.college')),
            ],
            options={
                'verbose_name': 'Fakulta vysoké školy',
                'verbose_name_plural': 'Fakulty vysokých škol',
                'ordering': ('name', 'college'),
                'unique_together': {('name', 'college')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Název', max_length=300)),
                ('city', models.CharField(help_text='Město', max_length=350)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena', max_digits=8)),
                ('study_length_in_semesters', models.IntegerField(help_text='Standardní doba studia')),
                ('study_form', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('prezencni', 'Prezenční forma studia'), ('distancni', 'Distanční forma sdtudia'), ('kombinovana', 'Kombinovaná forma studia')], help_text='Forma studia', max_length=20), blank=True, default=list, size=None)),
                ('major', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('jednoobor', 'Jednoobor'), ('dvouobor', 'Dvouobor')], help_text='Kombinace', max_length=20), blank=True, default=list, size=None)),
                ('url', models.URLField(help_text='URL na podrobnější informace', max_length=350)),
                ('note', models.TextField(blank=True, help_text='Poznámka')),
                ('education_specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.educationspecialization', verbose_name='Specializace')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.faculty', verbose_name='Fakulta')),
                ('other_qualification_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.otherexperience', verbose_name='Typ ostatní kvalifikace')),
                ('qualification_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.qualificationtype', verbose_name='Typ kvalifikace')),
                ('school_levels', models.ManyToManyField(to='teaching.SchoolLevel', verbose_name='Stupně škol')),
                ('subjects', models.ManyToManyField(to='teaching.Subject', verbose_name='Předměty')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.title', verbose_name='Titul')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.college', verbose_name='Vysoká škola')),
            ],
            options={
                'verbose_name': 'Kurz',
                'verbose_name_plural': 'Kurzy',
                'ordering': ('name', 'faculty', 'faculty__college'),
            },
        ),
    ]
