# Generated by Django 3.1.5 on 2021-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('name',), 'verbose_name': 'Vysoká škola', 'verbose_name_plural': 'Vysoké školy'},
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Adresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='databox',
            field=models.CharField(default='', max_length=20, verbose_name='Datová schránka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='form',
            field=models.CharField(choices=[('soukroma', 'soukromá'), ('statni', 'státní'), ('verejna', 'veřejná')], default='', max_length=20, verbose_name='Forma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='ic',
            field=models.CharField(default='', max_length=20, verbose_name='IČ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Název školy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='rid',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='RID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('univerzitni', 'univerzitní'), ('neuniverzitni', 'neuniverzitní')], default='', max_length=20, verbose_name='Typ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='rid',
            field=models.CharField(default='', max_length=20, verbose_name='RID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='town',
            field=models.CharField(default='', max_length=50, verbose_name='Město'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('name', 'college')},
        ),
    ]
