# Generated by Django 3.1.5 on 2021-01-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('name', 'college')},
        ),
    ]
