# Generated by Django 3.1.5 on 2021-06-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_schoolsubtype'),
        
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sds',
            new_name='study_length_in_semesters',
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.collegearea', verbose_name='Oblast VŠ vzdělávání'),
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Město'),
        ),
        migrations.AddField(
            model_name='course',
            name='double_major',
            field=models.BooleanField(default=False, verbose_name='Dvouobor'),
        ),
        migrations.AddField(
            model_name='course',
            name='form_distant',
            field=models.BooleanField(default=False, verbose_name='Distanční forma studia'),
        ),
        migrations.AddField(
            model_name='course',
            name='other_qualification_type',
            field=models.CharField(default='', max_length=150, verbose_name='Typ ostatní kvalifikace'),
        ),
        migrations.AddField(
            model_name='course',
            name='qualification_type',
            field=models.CharField(default='', max_length=150, verbose_name='Typ kvalifikace'),
        ),
        migrations.AddField(
            model_name='course',
            name='school_levels',
            field=models.ManyToManyField(to='teaching.SchoolLevel', verbose_name='Stupně škol'),
        ),
        migrations.AddField(
            model_name='course',
            name='single_major',
            field=models.BooleanField(default=True, verbose_name='Jednoobor'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Titul'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.college', verbose_name='Vysoká škola'),
        ),
    ]
