# Generated by Django 3.1.5 on 2021-02-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20210129_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='town',
        ),
    ]
