# Generated by Django 3.1.5 on 2021-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20210622_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='area',
        ),
        migrations.AlterField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('univerzitni', 'univerzitní'), ('neuniverzitni', 'neuniverzitní'), ('jazykova skola', 'jazyková škola')], max_length=20, verbose_name='Typ'),
        ),
    ]
