# Generated by Django 3.1.5 on 2021-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_auto_20210624_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.CharField(max_length=350, verbose_name='Město'),
        ),
    ]
