# Generated by Django 3.1.5 on 2021-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_auto_20210625_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL na podrobnější informace'),
        ),
    ]
