# Generated by Django 3.1.5 on 2021-06-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_auto_20210625_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(help_text='Adresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(help_text='Zkratka', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='databox',
            field=models.CharField(help_text='Datová schránka', max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='form',
            field=models.CharField(choices=[('soukroma', 'soukromá'), ('statni', 'státní'), ('verejna', 'veřejná')], help_text='Forma', max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='ic',
            field=models.CharField(help_text='IČ', max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(help_text='Název školy', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='rid',
            field=models.CharField(help_text='RID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('univerzitni', 'univerzitní'), ('neuniverzitni', 'neuniverzitní'), ('jazykova skola', 'jazyková škola')], help_text='Typ', max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='url',
            field=models.URLField(help_text='URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.CharField(help_text='Město', max_length=350),
        ),
        migrations.AlterField(
            model_name='course',
            name='double_major',
            field=models.BooleanField(default=False, help_text='Dvouobor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='form_combined',
            field=models.BooleanField(default=True, help_text='Kombinovaná forma studia'),
        ),
        migrations.AlterField(
            model_name='course',
            name='form_distant',
            field=models.BooleanField(default=False, help_text='Distanční forma studia'),
        ),
        migrations.AlterField(
            model_name='course',
            name='form_present',
            field=models.BooleanField(default=False, help_text='Prezenční forma studia'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Název', max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='note',
            field=models.TextField(blank=True, help_text='Poznámka'),
        ),
        migrations.AlterField(
            model_name='course',
            name='other_qualification_type',
            field=models.CharField(help_text='Typ ostatní kvalifikace', max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Cena', max_digits=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='qualification_type',
            field=models.CharField(help_text='Typ kvalifikace', max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='single_major',
            field=models.BooleanField(default=True, help_text='Jednoobor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_length_in_semesters',
            field=models.IntegerField(help_text='Standardní doba studia'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(help_text='URL na podrobnější informace', max_length=350),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(help_text='Název fakulty', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rid',
            field=models.CharField(help_text='RID', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='url',
            field=models.URLField(help_text='URL'),
        ),
    ]
