# Generated by Django 3.1.5 on 2021-09-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_auto_20210630_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='education_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.educationspecialization', verbose_name='Specializace'),
        ),
    ]
