---
version: '2'

services:

  app:
    container_name: zuapp
    image: msgre/zuapp:latest
    build: .
    volumes:
      - $PWD:/app/
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_NAME: zu
      DATABASE_USER: zu
      DATABASE_PASSWORD: heslo
      DATABASE_HOST: db
      DJANGO_SECRET: "o+=_^p))1+)cu^c#ce^3@k0pdb^#jr**h)0txi&^yw00chze^+:"
    ports:
      - "8300:8300"
      - "8301:8301"
    stop_signal: SIGINT
    working_dir: /zacni-ucit
    command: ./manage.py runserver zuapp:8300
    links:
      - db
    depends_on:
      - db

  db:
    container_name: zudb
    image: postgres:9.5.20
    environment:
      POSTGRES_PASSWORD: heslo
      POSTGRES_USER: zu
      POSTGRES_DB: zu
    # volumes:
    #   - $PWD/importdb.sh:/docker-entrypoint-initdb.d/importdb.sh
    #   - $PWD/db.dump:/db.dump
