# Generated by Django 3.1.5 on 2021-01-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20210125_0915'),
        ('rvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name', 'faculty', 'faculty__college'), 'verbose_name': 'Kurz', 'verbose_name_plural': 'Kurzy'},
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.faculty', verbose_name='Fakulta'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='rvp.Subject', verbose_name='Předměty'),
        ),
    ]
