# Generated by Django 3.1.5 on 2021-01-29 14:49

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název oblasti')),
            ],
            options={
                'verbose_name': 'Oblast VŠ vzdělávání',
                'verbose_name_plural': 'Oblasti VŠ vzdělávání',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Zkratka')),
            ],
            options={
                'verbose_name': 'Titul',
                'verbose_name_plural': 'Tituly',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('qualification', models.CharField(choices=[('titul', 'Titul'), ('czv', 'Kurz CŽV'), ('dalsi', 'Další možnosti')], max_length=20, verbose_name='Možnosti získání kvalifikace')),
                ('education', models.CharField(max_length=200, verbose_name='Typ vzdělání z hlediska zákona')),
            ],
            options={
                'verbose_name': 'Typ vzdělání z hlediska zákona',
                'verbose_name_plural': 'Typ vzdělání z hlediska zákona',
                'ordering': ('education',),
                'unique_together': {('qualification', 'education')},
            },
        ),
        migrations.CreateModel(
            name='CollegeProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Studijní program')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.collegearea', verbose_name='Oblast VŠ vzdělávání')),
                ('subjects', models.ManyToManyField(help_text='Co můžeš učit na 2.stupni ZŠ nebo na SŠ.', to='teaching.Subject', verbose_name='Vzdělávací oblast podle RVP')),
            ],
            options={
                'verbose_name': 'Typický VŠ studijní program',
                'verbose_name_plural': 'Typické VŠ studijní programy',
                'ordering': ('area', 'name'),
                'unique_together': {('area', 'name')},
            },
        ),
    ]
