# Generated by Django 3.1.5 on 2021-02-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_schoollevel_schooltype_subjectgroup'),
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationtype',
            options={'ordering': ('qualification_type',), 'verbose_name': 'Typ vzdělání z hlediska zákona', 'verbose_name_plural': 'Typ vzdělání z hlediska zákona'},
        ),
        migrations.AddField(
            model_name='educationtype',
            name='area',
            field=models.CharField(max_length=512, null=True, verbose_name='Oblast VŠ vzdělávání'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='preparation_type',
            field=models.CharField(max_length=200, null=True, verbose_name='Typ přípravy učitelů'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='qualification_type',
            field=models.CharField(choices=[('titul', 'Titul'), ('czv', 'Kurz CŽV'), ('dalsi', 'Další možnosti')], default='TITUL', max_length=20, verbose_name='Typ kvalifikace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationtype',
            name='school_levels',
            field=models.ManyToManyField(null=True, to='teaching.SchoolLevel'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='subjects_type',
            field=models.CharField(max_length=512, null=True, verbose_name='Typ předmětů'),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualifications.title'),
        ),
        migrations.AlterUniqueTogether(
            name='educationtype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='education',
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='qualification',
        ),
    ]
