# Generated by Django 3.1.5 on 2021-02-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_schoollevel_subjects'),
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationtype',
            name='school_levels',
            field=models.ManyToManyField(related_name='education_types', to='teaching.SchoolLevel'),
        ),
    ]
