# Generated by Django 3.1.5 on 2021-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationtype',
            options={'ordering': ('id', 'qualification_type'), 'verbose_name': 'Typ vzdělání z hlediska zákona', 'verbose_name_plural': 'Typ vzdělání z hlediska zákona'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Kvalifikace', 'verbose_name_plural': 'Kvalifikace'},
        ),
        migrations.AlterField(
            model_name='qualification',
            name='subject_groups',
            field=models.ManyToManyField(to='teaching.SubjectGroup', verbose_name='Skupiny předmětů'),
        ),
    ]
