# Generated by Django 3.1.5 on 2021-11-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_auto_20211020_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtype',
            name='link_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='educationtype',
            name='name_edu_type',
            field=models.CharField(max_length=200, null=True, verbose_name='Název edu_type'),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Zákonná formulace'),
        ),
    ]
