# Generated by Django 3.1.5 on 2021-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20210928_1359'),
        ('qualifications', '0004_auto_20210928_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationtype',
            name='subject_groups',
            field=models.ManyToManyField(null=True, to='teaching.SubjectGroup', verbose_name='Skupina předmětů'),
        ),
    ]
