# Generated by Django 3.1.5 on 2021-08-22 13:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_schoolsubtype'),
        ('qualifications', '0004_auto_20210227_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Další možnost',
                'verbose_name_plural': 'Další možnosti',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='preparationtype',
            options={'ordering': ('name',), 'verbose_name': 'Typ předmětů', 'verbose_name_plural': 'Typy předmětů'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'ordering': ('name',), 'verbose_name': 'Typ předmětů', 'verbose_name_plural': 'Tipy předmětů'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'code'), 'verbose_name': 'Titul', 'verbose_name_plural': 'Tituly'},
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='subject_type',
        ),

        migrations.AddField(
            model_name='educationtype',
            name='subject_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.subjectgroup', verbose_name='Skupina předmětů'),
        ),
        migrations.AddField(
            model_name='title',
            name='visible_in_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='qualification_type',
            field=models.CharField(choices=[('titul', 'Titul'), ('czv', 'Kurz CŽV'), ('dalsi', 'Další zkušenost')], max_length=20, verbose_name='Typ kvalifikace'),
        ),

    ]
