# Generated by Django 3.1.5 on 2021-03-02 18:36

import common.models
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0004_auto_20210227_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Další možnost',
                'verbose_name_plural': 'Další možnosti',
                'ordering': ('name',),
            },
            bases=(models.Model, common.models.GraphModel),
        ),
    ]
