# Generated by Django 3.1.5 on 2021-06-15 18:32

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_schoolsubtype'),
        ('qualifications', '0005_otheroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('legal_paragraph', models.CharField(max_length=400, unique=True, verbose_name='Paragraf zákona')),
                ('example', models.CharField(max_length=400, unique=True, verbose_name='Paragraf zákona')),
                ('row_id', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Kvalifikace',
                'verbose_name_plural': 'Kvalifikace',
                'ordering': ('row_id', 'legal_paragraph', 'example'),
            },
            bases=(models.Model, common.models.GraphModel),
        ),
        migrations.RenameModel(
            old_name='OtherOption',
            new_name='OtherExperience',
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='preparation_type',
        ),
        migrations.AddField(
            model_name='educationtype',
            name='character',
            field=models.CharField(default='test_charakter', max_length=100, verbose_name='Charakter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationtype',
            name='name',
            field=models.CharField(default='name', max_length=200, verbose_name='Název'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='qualification_type',
            field=models.CharField(choices=[('titul', 'Titul'), ('czv', 'Kurz CŽV'), ('dalsi', 'Další zkušenost')], max_length=20, verbose_name='Typ kvalifikace'),
        ),
        migrations.DeleteModel(
            name='PreparationType',
        ),
        migrations.AddField(
            model_name='qualification',
            name='education_types',
            field=models.ManyToManyField(help_text='Typ vzdělání z hlediska zákona', to='qualifications.EducationType', verbose_name='Typ vzdělání z hlediska zákona'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='school_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='teaching.schoollevel', verbose_name='Stupeň školy'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='subject_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='qualifications.subjecttype', verbose_name='Typ předmětů'),
        ),
    ]
