# Generated by Django 3.1.5 on 2021-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0005_auto_20210928_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationtype',
            name='specialization',
        ),
        migrations.AddField(
            model_name='educationtype',
            name='specializations',
            field=models.ManyToManyField(null=True, to='qualifications.EducationSpecialization', verbose_name='Oblast VŠ vzdělávání'),
        ),
    ]
