# Generated by Django 3.1.5 on 2021-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0006_auto_20210615_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='note',
            field=models.TextField(blank=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='example',
            field=models.CharField(max_length=400, unique=True, verbose_name='Příklad'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='row_id',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
