# Generated by Django 3.1.5 on 2021-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0006_auto_20210822_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationArea',
            new_name='EducationSpecialization',
        ),
        migrations.AlterModelOptions(
            name='educationspecialization',
            options={'ordering': ('name',), 'verbose_name': 'Specializace', 'verbose_name_plural': 'Specializace'},
        ),
        migrations.RenameField(
            model_name='educationtype',
            old_name='area',
            new_name='specialization',
        ),

    ]
