# Generated by Django 3.1.5 on 2021-09-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0006_auto_20210928_1511'),
        ('qualifications', '0002_auto_20210920_1533'),
    ]

    operations = [
    ]
