# Generated by Django 3.1.5 on 2021-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0007_auto_20210628_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='example',
            field=models.TextField(unique=True, verbose_name='Příklad'),
        ),
    ]
