# Generated by Django 3.1.5 on 2021-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0007_auto_20210822_1644'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='qualification',
            name='example',
            field=models.CharField(max_length=700, unique=True, verbose_name='Příklad'),
        ),
    ]
