# Generated by Django 3.1.5 on 2021-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0008_auto_20210628_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='note',
            field=models.TextField(verbose_name='Poznámka'),
        ),
    ]
