# Generated by Django 3.1.5 on 2021-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0009_auto_20210822_1705'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='qualification',
            name='example',
            field=models.CharField(max_length=1000, verbose_name='Příklad'),
        ),
    ]
