# Generated by Django 3.1.5 on 2021-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0010_auto_20210628_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='legal_paragraph',
            field=models.CharField(max_length=400, verbose_name='Paragraf zákona'),
        ),
    ]
