export default [
  'Čeština',
  'Angličtina',
  'Němčina',
  'Francouzština',
  'Španělština',
  'Ruština',
  'Matematika',
  'IT',
  'Člověk a jeho svět',
  'Dějepis',
  'Občanská výchova',
  'Fyzika',
  'Chemie',
  'Přírodopis/Biologie',
];
