# Generated by Django 3.1.5 on 2021-01-23 15:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Název předmětu')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Zkratka')),
            ],
            options={
                'verbose_name': 'Vzdělávací oblast podle RVP',
                'verbose_name_plural': 'Vzdělávací oblasti podle RVP',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=300, verbose_name='Název')),
                ('price', models.IntegerField(verbose_name='Cena')),
                ('sds', models.IntegerField(verbose_name='Standardní doba studia')),
                ('form_present', models.BooleanField(default=False, verbose_name='Prezenční forma studia')),
                ('form_combined', models.BooleanField(default=True, verbose_name='Kombinovaná forma studia')),
                ('url', models.URLField(verbose_name='URL na podrobnější informace')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.faculty')),
                ('subjects', models.ManyToManyField(to='rvp.Subject')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
