export const routes = {
  homepage: '/',
  configurator: '/pruvodce',
  searchResults: '/vysledky-hledani',
  chooseSubject: '/vyber-predmetu',
  qualification: '/kvalifikace',
  workForEducation: '/prace-ve-skolstvi',
  teachingStart: '/zacinam-ucit',
  canITeach: '/muzu-ucit',
  tryToTeach: '/zkus-ucit',
  whyToTeach: '/proc-jit-ucit',
  wantToLearn: '/zauc-se',
  motivation: '/motivace',
  aboutUs: '/o-nas',
  partners: '/#partners',
  contact: '/kontakt',
  signUp: '/registrace',
  login: '/login',
  account: '/ucet',
  logout: '/logout',

  pedagogicMinimum: '/pedagogicke-minimum',
  missedTeachers: '/jaci-ucitele-chybi',
  isTeachingForMe: 'je-ucitelstvi-pro-me',
  completeQualification: 'chci-si-doplnit-kvalifikaci',
  chooseSchool: '/vybiram-skolu',
  pedagogicalLaw: '/zakon-o-ped-pracovnicich',
  dayForSchool: '/den-pro-skolu',
  teachersStories: '/pribehy-ucitelu',
  sallary: '/platy-ucitelu',
  canDoAtSchool: '/co-muzete-delat-ve-skole',
  jobs: '/volna-mista-ve-skolstvi',
  teachersTips: '/tipy-pro-zacinajici-ucitele',
  donate: '/pripejte-jinak',
  vyluka: '/vyluka',
};
