export const routes = {
  homepage: '/',
  configurator: '/pruvodce',
  searchResults: '/vysledky-hledani',
  chooseSubject: '/vyber-predmetu',
  qualification: '/kvalifikace',
  teachingStart: '/zacinam-ucit',
  canITeach: '/muzu-ucit',
  motivation: '/motivace',
  partners: '/partneri',
  contact: '/kontakt',
  signUp: '/registrace',
  login: '/login',
  account: '/ucet',
  logout: '/logout',

  isTeachingForMe: 'je-ucitelstvi-pro-me',
  chooseSchool: '/vybiram-skolu',
  pedagogicalLaw: '/zakon-o-ped-pracovnicich',
  sallary: '/platy-ucitelu',
  canDoAtSchool: '/co-muzete-delat-ve-skole',
  jobs: '/volna-mista-ve-skolstvi',
  donate: '/pripejte-jinak',

  aboutUs: '/o-vyluce',
  whyToTeach: '/proc-jit-ucit',
  tryTeaching: {
    main: '/chci-si-zkusit-uceni',
    howItWorks: '/chci-si-zkusit-uceni/jak-probiha-program',
  },
  learn: {
    main: '/chci-se-zaucit',
    howItWorks: '/chci-se-zaucit/jak-probiha-program',
  },
  startTeaching: {
    crossroad: '/muzu-ucit',
    completeYourQualification: '/muzu-ucit/kde-si-doplnit-kvalifikaci',
    kindergarten: '/muzu-ucit/jak-zacit-ucit-v-materske-skole',
    firstGrade: '/muzu-ucit/jak-zacit-ucit-na-1-stupni-zs',
    secondGrade: {
      crossroad: '/muzu-ucit/jak-zacit-ucit-na-2-stupni-zs',
      languages: '/muzu-ucit/jak-zacit-ucit-na-2-stupni-zs/cizi-jazyky',
      arts: '/muzu-ucit/jak-zacit-ucit-na-2-stupni-zs/umelecke-predmety',
      generalSubjects: '/muzu-ucit/jak-zacit-ucit-na-2-stupni-zs/vseobecne-predmety',
      gymnastics: '/muzu-ucit/jak-zacit-ucit-na-2-stupni-zs/telocvik',
    },
    highSchool: {
      crossroad: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole',
      languages: `/muzu-ucit/jak-zacit-ucit-na-stredni-skole/cizi-jazyky`,
      arts: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole/umelecke-predmety',
      generalSubjects: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole/vseobecne-predmety',
      gymnastics: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole/telocvik',
      vocationalSubjects: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole/odborne-predmety',
      practicalSubjects: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole/prakticke-vyucovani',
      practise: '/muzu-ucit/jak-zacit-ucit-na-stredni-skole/odborny-vycvik',
    },
    teacherAssistant: {
      crossroad: '/muzu-ucit/jak-zacit-delat-asistenta-pedagoga',
      lowerExpertise: '/muzu-ucit/jak-zacit-delat-asistenta-pedagoga/nizsi-odbornost',
      higherExpertise: '/muzu-ucit/jak-zacit-delat-asistenta-pedagoga/vyssi-odbornost',
    },
  },
};
