name: Checker

on: push

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Black formatter check
        uses: jpetrucciani/black-check@master
