name: 'Terraform Apply on push'
on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/aws/**'
env:
  tf_version: '0.14.7'
  tf_working_dir: 'infrastructure/aws'
  TF_VAR_database-password: ${{ secrets.DATABASE_PASSWORD }}
  TF_VAR_neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
  TF_VAR_django-secret: ${{ secrets.DJANGO_SECRET }}
  TF_VAR_sendgrid-api-key: ${{ secrets.SENDGRID_API_KEY }}
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

